[[package]]
name = "apt-file"
brew = []

[[package]]
name = "binutils"
check = "strings"

[[package]]
name = "black"

[[package]]
name = "colordiff"

[[package]]
name = "dig"
apt = "dnsutils"
brew = "bind"

[[package]]
name = "emacs"
apt = "emacs-nox"

[[package]]
name = "figlet"

[[package]]
name = "fzf"

[[package]]
name = "git"

[[package]]
name = "graphviz"
check = "dot"

[[package]]
name = "ghostscript"
check = "gs"

[[package]]
name = "htop"

[[package]]
name = "ispell"
brew = []

[[package]]
name = "jq"

[[package]]
name = "kpcli"
brew = []

[[package]]
name = "make"

[[package]]
name = "nano"

[[package]]
name = "pip3"
apt = ["python3-pip", "python3-venv"]
brew = "python"

[[package]]
name = "python3"
apt = ["python3-pip", "python3-venv"]
brew = "python"

[[package]]
name = "rg"
apt = "ripgrep"
brew = "ripgrep"

[[package]]
name = "screen"

[[package]]
name = "stow"
linux_check = "xstow"
darwin_check = "stow"
apt = "xstow"
brew = "stow"

[[package]]
name = "tree"

[[package]]
name = "zsh"
