alias ll="ls -la"
alias emacs="emacs -nw"
alias djvu2pdf="ddjvu -format=pdf -quality=85 -verbose"
alias lll="ll|pager"
alias gitsub="git submodule foreach 'git fetch origin --tags; git checkout master; git pull' && git pull && git submodule update --init --recursive"